CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    milk_company_name VARCHAR(150),
    phone_number VARCHAR(20) UNIQUE,
    email VARCHAR(100) UNIQUE,
    password VARCHAR(255),
    telegram_id VARCHAR(100) UNIQUE,
    role VARCHAR(50),
    status VARCHAR(50),
    profile_image VARCHAR(255),
    trial_start_date DATETIME,
    trial_end_date DATETIME,
    subscription_end_date DATETIME,
    is_blocked BOOLEAN DEFAULT FALSE,
    subscription_plan_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
