CREATE TABLE customers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    telegram_id VARCHAR(100),
    address VARCHAR(255),
    latitude DOUBLE,
    longitude DOUBLE,
    milk_quantity DOUBLE NOT NULL,
    extra_milk DOUBLE DEFAULT 0.0,
    extra_milk_days INT DEFAULT 0,
    is_paused BOOLEAN DEFAULT FALSE,
    pause_days INT DEFAULT 0,
    pause_start_date DATE,
    pause_end_date DATE,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    delivery_completed BOOLEAN DEFAULT FALSE NOT NULL,
    milk_category_id BIGINT,
    user_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (milk_category_id) REFERENCES milk_categories(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
